[2024-04-08T02:03:06.690+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_congress_data.bill_status_external_table_task manual__2024-04-08T02:00:46.341975+00:00 [queued]>
[2024-04-08T02:03:06.695+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_congress_data.bill_status_external_table_task manual__2024-04-08T02:00:46.341975+00:00 [queued]>
[2024-04-08T02:03:06.696+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-04-08T02:03:06.701+0000] {taskinstance.py:2217} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bill_status_external_table_task> on 2024-04-08 02:00:46.341975+00:00
[2024-04-08T02:03:06.706+0000] {standard_task_runner.py:60} INFO - Started process 4720 to run task
[2024-04-08T02:03:06.708+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_congress_data', 'bill_status_external_table_task', 'manual__2024-04-08T02:00:46.341975+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/upload_congress_data.py', '--cfg-path', '/tmp/tmp2pgr5_4i']
[2024-04-08T02:03:06.710+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask bill_status_external_table_task
[2024-04-08T02:03:06.738+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_congress_data.bill_status_external_table_task manual__2024-04-08T02:00:46.341975+00:00 [running]> on host 429434a1f011
[2024-04-08T02:03:06.848+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_congress_data' AIRFLOW_CTX_TASK_ID='bill_status_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T02:00:46.341975+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-08T02:00:46.341975+00:00'
[2024-04-08T02:03:06.850+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-04-08T02:03:06.851+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-08T02:03:06.851+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-04-08T02:03:07.399+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1783, in execute
    table = bq_hook.create_empty_table(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/common/hooks/base_google.py", line 485, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 422, in create_empty_table
    return self.get_client(project_id=project_id, location=location).create_table(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/bigquery/client.py", line 797, in create_table
    api_response = self._call_api(
                   ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/bigquery/client.py", line 831, in _call_api
    return call()
           ^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.11/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/inbound-ship-412204/datasets/Congress/tables?prettyPrint=false: Invalid value for type: ARRAY is not a valid value
[2024-04-08T02:03:07.427+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_congress_data, task_id=bill_status_external_table_task, execution_date=20240408T020046, start_date=20240408T020306, end_date=20240408T020307
[2024-04-08T02:03:07.441+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 29 for task bill_status_external_table_task (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/inbound-ship-412204/datasets/Congress/tables?prettyPrint=false: Invalid value for type: ARRAY is not a valid value; 4720)
[2024-04-08T02:03:07.465+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-08T02:03:07.478+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
