[2024-03-28T03:24:14.917+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.member_external_table_task scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-03-28T03:24:14.925+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.member_external_table_task scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-03-28T03:24:14.927+0000] {taskinstance.py:2193} INFO - Starting attempt 6 of 6
[2024-03-28T03:24:14.936+0000] {taskinstance.py:2217} INFO - Executing <Task(BigQueryCreateExternalTableOperator): member_external_table_task> on 2024-03-15 00:00:00+00:00
[2024-03-28T03:24:14.944+0000] {standard_task_runner.py:60} INFO - Started process 150 to run task
[2024-03-28T03:24:14.948+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'member_external_table_task', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmpbwlk_lxy']
[2024-03-28T03:24:14.952+0000] {standard_task_runner.py:88} INFO - Job 146: Subtask member_external_table_task
[2024-03-28T03:24:14.998+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.member_external_table_task scheduled__2024-03-15T00:00:00+00:00 [running]> on host be5d54f7fe24
[2024-03-28T03:24:15.050+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='member_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-03-28T03:24:15.053+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-03-28T03:24:15.054+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-28T03:24:15.056+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-03-28T03:24:15.650+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1783, in execute
    table = bq_hook.create_empty_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 485, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 422, in create_empty_table
    return self.get_client(project_id=project_id, location=location).create_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 797, in create_table
    api_response = self._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 831, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/inbound-ship-412204/datasets/Congress/tables?prettyPrint=false: Invalid value for type: STRUCT<CHAMBER STRING, ENDYEAR INT64, STARTYEAR INT64> is not a valid value
[2024-03-28T03:24:15.671+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=upload_historical_congress_data, task_id=member_external_table_task, execution_date=20240315T000000, start_date=20240328T032414, end_date=20240328T032415
[2024-03-28T03:24:15.687+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 146 for task member_external_table_task (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/inbound-ship-412204/datasets/Congress/tables?prettyPrint=false: Invalid value for type: STRUCT<CHAMBER STRING, ENDYEAR INT64, STARTYEAR INT64> is not a valid value; 150)
[2024-03-28T03:24:15.718+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-28T03:24:15.775+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
