[2024-04-01T03:21:10.091+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-01T03:21:10.095+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-01T03:21:10.096+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-04-01T03:21:10.101+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_and_upload_votes_to_gcs> on 2024-03-15 00:00:00+00:00
[2024-04-01T03:21:10.108+0000] {standard_task_runner.py:60} INFO - Started process 443 to run task
[2024-04-01T03:21:10.111+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'get_and_upload_votes_to_gcs', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmpk2x4ynpb']
[2024-04-01T03:21:10.113+0000] {standard_task_runner.py:88} INFO - Job 61: Subtask get_and_upload_votes_to_gcs
[2024-04-01T03:21:10.143+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [running]> on host 506660a4b8e3
[2024-04-01T03:21:10.418+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='get_and_upload_votes_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-01T03:21:10.419+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python/get_data.py", line 115, in get_and_upload_votes
    params['bill_number'] = bill[1]
                            ~~~~^^^
IndexError: string index out of range
[2024-04-01T03:21:10.424+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_historical_congress_data, task_id=get_and_upload_votes_to_gcs, execution_date=20240315T000000, start_date=20240401T032110, end_date=20240401T032110
[2024-04-01T03:21:10.432+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 61 for task get_and_upload_votes_to_gcs (string index out of range; 443)
[2024-04-01T03:21:10.458+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T03:21:10.473+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T03:04:02.388+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:04:02.393+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:04:02.393+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-04-02T03:04:02.398+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_and_upload_votes_to_gcs> on 2024-03-15 00:00:00+00:00
[2024-04-02T03:04:02.402+0000] {standard_task_runner.py:60} INFO - Started process 82 to run task
[2024-04-02T03:04:02.404+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'get_and_upload_votes_to_gcs', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmp21c2ly9q']
[2024-04-02T03:04:02.406+0000] {standard_task_runner.py:88} INFO - Job 97: Subtask get_and_upload_votes_to_gcs
[2024-04-02T03:04:02.434+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [running]> on host 308c9d5b795d
[2024-04-02T03:04:02.482+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='get_and_upload_votes_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-02T03:04:02.483+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python/get_data.py", line 115, in get_and_upload_votes
    params['bill_number'] = bill[1]
                            ~~~~^^^
IndexError: string index out of range
[2024-04-02T03:04:02.488+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_historical_congress_data, task_id=get_and_upload_votes_to_gcs, execution_date=20240315T000000, start_date=20240402T030402, end_date=20240402T030402
[2024-04-02T03:04:02.494+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 97 for task get_and_upload_votes_to_gcs (string index out of range; 82)
[2024-04-02T03:04:02.543+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T03:04:02.558+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T03:13:04.052+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:13:04.057+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:13:04.057+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-04-02T03:13:04.063+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_and_upload_votes_to_gcs> on 2024-03-15 00:00:00+00:00
[2024-04-02T03:13:04.068+0000] {standard_task_runner.py:60} INFO - Started process 256 to run task
[2024-04-02T03:13:04.070+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'get_and_upload_votes_to_gcs', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmp89iy8599']
[2024-04-02T03:13:04.073+0000] {standard_task_runner.py:88} INFO - Job 115: Subtask get_and_upload_votes_to_gcs
[2024-04-02T03:13:04.100+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [running]> on host 308c9d5b795d
[2024-04-02T03:13:04.152+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='get_and_upload_votes_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-02T03:13:04.153+0000] {get_data.py:115} INFO - Congress = [
[2024-04-02T03:13:04.154+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python/get_data.py", line 116, in get_and_upload_votes
    params['bill_number'] = bill[1]
                            ~~~~^^^
IndexError: string index out of range
[2024-04-02T03:13:04.159+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_historical_congress_data, task_id=get_and_upload_votes_to_gcs, execution_date=20240315T000000, start_date=20240402T031304, end_date=20240402T031304
[2024-04-02T03:13:04.165+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 115 for task get_and_upload_votes_to_gcs (string index out of range; 256)
[2024-04-02T03:13:04.206+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T03:13:04.221+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T03:40:52.494+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:40:52.498+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:40:52.498+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-04-02T03:40:52.503+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_and_upload_votes_to_gcs> on 2024-03-15 00:00:00+00:00
[2024-04-02T03:40:52.509+0000] {standard_task_runner.py:60} INFO - Started process 81 to run task
[2024-04-02T03:40:52.511+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'get_and_upload_votes_to_gcs', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmpz30tijhi']
[2024-04-02T03:40:52.513+0000] {standard_task_runner.py:88} INFO - Job 128: Subtask get_and_upload_votes_to_gcs
[2024-04-02T03:40:52.539+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [running]> on host 308c9d5b795d
[2024-04-02T03:40:52.583+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='get_and_upload_votes_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-02T03:40:52.585+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_and_upload_votes() missing 1 required positional argument: 'bills_list'
[2024-04-02T03:40:52.589+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_historical_congress_data, task_id=get_and_upload_votes_to_gcs, execution_date=20240315T000000, start_date=20240402T034052, end_date=20240402T034052
[2024-04-02T03:40:52.596+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 128 for task get_and_upload_votes_to_gcs (get_and_upload_votes() missing 1 required positional argument: 'bills_list'; 81)
[2024-04-02T03:40:52.604+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T03:40:52.619+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T04:01:10.987+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T04:01:10.992+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T04:01:10.992+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-04-02T04:01:10.997+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_and_upload_votes_to_gcs> on 2024-03-15 00:00:00+00:00
[2024-04-02T04:01:11.002+0000] {standard_task_runner.py:60} INFO - Started process 115 to run task
[2024-04-02T04:01:11.004+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'get_and_upload_votes_to_gcs', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmpupmr8f14']
[2024-04-02T04:01:11.006+0000] {standard_task_runner.py:88} INFO - Job 156: Subtask get_and_upload_votes_to_gcs
[2024-04-02T04:01:11.033+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [running]> on host 308c9d5b795d
[2024-04-02T04:01:11.075+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='get_and_upload_votes_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-02T04:01:11.076+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python/get_data.py", line 116, in get_and_upload_votes
    bills_list = ti.xcom_pull(key='bills_list', task_ids="get_bills_from_bq")
                 ^^
NameError: name 'ti' is not defined
[2024-04-02T04:01:11.081+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_historical_congress_data, task_id=get_and_upload_votes_to_gcs, execution_date=20240315T000000, start_date=20240402T040110, end_date=20240402T040111
[2024-04-02T04:01:11.086+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 156 for task get_and_upload_votes_to_gcs (name 'ti' is not defined; 115)
[2024-04-02T04:01:11.098+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T04:01:11.112+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
