[2024-04-01T03:22:11.880+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-01T03:22:11.884+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-01T03:22:11.884+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-04-01T03:22:11.890+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_and_upload_votes_to_gcs> on 2024-03-15 00:00:00+00:00
[2024-04-01T03:22:11.894+0000] {standard_task_runner.py:60} INFO - Started process 460 to run task
[2024-04-01T03:22:11.896+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'get_and_upload_votes_to_gcs', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmp5f459kn0']
[2024-04-01T03:22:11.898+0000] {standard_task_runner.py:88} INFO - Job 62: Subtask get_and_upload_votes_to_gcs
[2024-04-01T03:22:11.924+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [running]> on host 506660a4b8e3
[2024-04-01T03:22:12.165+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='get_and_upload_votes_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-01T03:22:12.166+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python/get_data.py", line 115, in get_and_upload_votes
    params['bill_number'] = bill[1]
                            ~~~~^^^
IndexError: string index out of range
[2024-04-01T03:22:12.171+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_historical_congress_data, task_id=get_and_upload_votes_to_gcs, execution_date=20240315T000000, start_date=20240401T032211, end_date=20240401T032212
[2024-04-01T03:22:12.176+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 62 for task get_and_upload_votes_to_gcs (string index out of range; 460)
[2024-04-01T03:22:12.219+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T03:22:12.234+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T03:05:03.506+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:05:03.511+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:05:03.512+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-04-02T03:05:03.518+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_and_upload_votes_to_gcs> on 2024-03-15 00:00:00+00:00
[2024-04-02T03:05:03.522+0000] {standard_task_runner.py:60} INFO - Started process 99 to run task
[2024-04-02T03:05:03.524+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'get_and_upload_votes_to_gcs', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmprj4qnepy']
[2024-04-02T03:05:03.527+0000] {standard_task_runner.py:88} INFO - Job 98: Subtask get_and_upload_votes_to_gcs
[2024-04-02T03:05:03.565+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [running]> on host 308c9d5b795d
[2024-04-02T03:05:03.617+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='get_and_upload_votes_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-02T03:05:03.618+0000] {get_data.py:115} INFO - Congress = [
[2024-04-02T03:05:03.618+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python/get_data.py", line 116, in get_and_upload_votes
    params['bill_number'] = bill[1]
                            ~~~~^^^
IndexError: string index out of range
[2024-04-02T03:05:03.623+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_historical_congress_data, task_id=get_and_upload_votes_to_gcs, execution_date=20240315T000000, start_date=20240402T030503, end_date=20240402T030503
[2024-04-02T03:05:03.628+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 98 for task get_and_upload_votes_to_gcs (string index out of range; 99)
[2024-04-02T03:05:03.657+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T03:05:03.672+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T03:14:05.081+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:14:05.085+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:14:05.085+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-04-02T03:14:05.091+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_and_upload_votes_to_gcs> on 2024-03-15 00:00:00+00:00
[2024-04-02T03:14:05.097+0000] {standard_task_runner.py:60} INFO - Started process 273 to run task
[2024-04-02T03:14:05.099+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'get_and_upload_votes_to_gcs', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmpumz8u9p5']
[2024-04-02T03:14:05.102+0000] {standard_task_runner.py:88} INFO - Job 116: Subtask get_and_upload_votes_to_gcs
[2024-04-02T03:14:05.134+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [running]> on host 308c9d5b795d
[2024-04-02T03:14:05.183+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='get_and_upload_votes_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-02T03:14:05.184+0000] {get_data.py:115} INFO - Congress = [
[2024-04-02T03:14:05.185+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python/get_data.py", line 116, in get_and_upload_votes
    params['bill_number'] = bill[1]
                            ~~~~^^^
IndexError: string index out of range
[2024-04-02T03:14:05.189+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_historical_congress_data, task_id=get_and_upload_votes_to_gcs, execution_date=20240315T000000, start_date=20240402T031405, end_date=20240402T031405
[2024-04-02T03:14:05.194+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 116 for task get_and_upload_votes_to_gcs (string index out of range; 273)
[2024-04-02T03:14:05.236+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T03:14:05.252+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T03:41:54.251+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:41:54.259+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:41:54.259+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-04-02T03:41:54.266+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_and_upload_votes_to_gcs> on 2024-03-15 00:00:00+00:00
[2024-04-02T03:41:54.272+0000] {standard_task_runner.py:60} INFO - Started process 98 to run task
[2024-04-02T03:41:54.275+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'get_and_upload_votes_to_gcs', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmpa66wtvsl']
[2024-04-02T03:41:54.278+0000] {standard_task_runner.py:88} INFO - Job 129: Subtask get_and_upload_votes_to_gcs
[2024-04-02T03:41:54.316+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [running]> on host 308c9d5b795d
[2024-04-02T03:41:54.362+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='get_and_upload_votes_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-02T03:41:54.363+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_and_upload_votes() missing 1 required positional argument: 'bills_list'
[2024-04-02T03:41:54.368+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_historical_congress_data, task_id=get_and_upload_votes_to_gcs, execution_date=20240315T000000, start_date=20240402T034154, end_date=20240402T034154
[2024-04-02T03:41:54.376+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 129 for task get_and_upload_votes_to_gcs (get_and_upload_votes() missing 1 required positional argument: 'bills_list'; 98)
[2024-04-02T03:41:54.408+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T03:41:54.426+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T04:02:12.055+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T04:02:12.059+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T04:02:12.060+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-04-02T04:02:12.065+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_and_upload_votes_to_gcs> on 2024-03-15 00:00:00+00:00
[2024-04-02T04:02:12.070+0000] {standard_task_runner.py:60} INFO - Started process 132 to run task
[2024-04-02T04:02:12.073+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'get_and_upload_votes_to_gcs', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmpwcria6wb']
[2024-04-02T04:02:12.076+0000] {standard_task_runner.py:88} INFO - Job 157: Subtask get_and_upload_votes_to_gcs
[2024-04-02T04:02:12.106+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [running]> on host 308c9d5b795d
[2024-04-02T04:02:12.155+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='get_and_upload_votes_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-02T04:02:12.157+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python/get_data.py", line 116, in get_and_upload_votes
    bills_list = ti.xcom_pull(key='bills_list', task_ids="get_bills_from_bq")
                 ^^
NameError: name 'ti' is not defined
[2024-04-02T04:02:12.161+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_historical_congress_data, task_id=get_and_upload_votes_to_gcs, execution_date=20240315T000000, start_date=20240402T040212, end_date=20240402T040212
[2024-04-02T04:02:12.167+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 157 for task get_and_upload_votes_to_gcs (name 'ti' is not defined; 132)
[2024-04-02T04:02:12.207+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T04:02:12.227+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
