[2024-04-01T03:23:13.850+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-01T03:23:13.854+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-01T03:23:13.855+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-04-01T03:23:13.861+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_and_upload_votes_to_gcs> on 2024-03-15 00:00:00+00:00
[2024-04-01T03:23:13.865+0000] {standard_task_runner.py:60} INFO - Started process 477 to run task
[2024-04-01T03:23:13.867+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'get_and_upload_votes_to_gcs', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmpm48tf_5h']
[2024-04-01T03:23:13.869+0000] {standard_task_runner.py:88} INFO - Job 63: Subtask get_and_upload_votes_to_gcs
[2024-04-01T03:23:13.897+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [running]> on host 506660a4b8e3
[2024-04-01T03:23:14.133+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='get_and_upload_votes_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-01T03:23:14.134+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python/get_data.py", line 115, in get_and_upload_votes
    params['bill_number'] = bill[1]
                            ~~~~^^^
IndexError: string index out of range
[2024-04-01T03:23:14.139+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=upload_historical_congress_data, task_id=get_and_upload_votes_to_gcs, execution_date=20240315T000000, start_date=20240401T032313, end_date=20240401T032314
[2024-04-01T03:23:14.144+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 63 for task get_and_upload_votes_to_gcs (string index out of range; 477)
[2024-04-01T03:23:14.174+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T03:23:14.190+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T03:06:05.050+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:06:05.054+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:06:05.054+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-04-02T03:06:05.060+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_and_upload_votes_to_gcs> on 2024-03-15 00:00:00+00:00
[2024-04-02T03:06:05.064+0000] {standard_task_runner.py:60} INFO - Started process 116 to run task
[2024-04-02T03:06:05.067+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'get_and_upload_votes_to_gcs', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmpwsh88wmv']
[2024-04-02T03:06:05.069+0000] {standard_task_runner.py:88} INFO - Job 99: Subtask get_and_upload_votes_to_gcs
[2024-04-02T03:06:05.100+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [running]> on host 308c9d5b795d
[2024-04-02T03:06:05.150+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='get_and_upload_votes_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-02T03:06:05.151+0000] {get_data.py:115} INFO - Congress = [
[2024-04-02T03:06:05.151+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python/get_data.py", line 116, in get_and_upload_votes
    params['bill_number'] = bill[1]
                            ~~~~^^^
IndexError: string index out of range
[2024-04-02T03:06:05.156+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=upload_historical_congress_data, task_id=get_and_upload_votes_to_gcs, execution_date=20240315T000000, start_date=20240402T030605, end_date=20240402T030605
[2024-04-02T03:06:05.162+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 99 for task get_and_upload_votes_to_gcs (string index out of range; 116)
[2024-04-02T03:06:05.201+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T03:06:05.215+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T03:15:06.621+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:15:06.625+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:15:06.625+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-04-02T03:15:06.631+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_and_upload_votes_to_gcs> on 2024-03-15 00:00:00+00:00
[2024-04-02T03:15:06.636+0000] {standard_task_runner.py:60} INFO - Started process 290 to run task
[2024-04-02T03:15:06.639+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'get_and_upload_votes_to_gcs', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmpr1o6y2er']
[2024-04-02T03:15:06.642+0000] {standard_task_runner.py:88} INFO - Job 117: Subtask get_and_upload_votes_to_gcs
[2024-04-02T03:15:06.671+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [running]> on host 308c9d5b795d
[2024-04-02T03:15:06.722+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='get_and_upload_votes_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-02T03:15:06.723+0000] {get_data.py:115} INFO - Congress = [
[2024-04-02T03:15:06.723+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python/get_data.py", line 116, in get_and_upload_votes
    params['bill_number'] = bill[1]
                            ~~~~^^^
IndexError: string index out of range
[2024-04-02T03:15:06.729+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=upload_historical_congress_data, task_id=get_and_upload_votes_to_gcs, execution_date=20240315T000000, start_date=20240402T031506, end_date=20240402T031506
[2024-04-02T03:15:06.735+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 117 for task get_and_upload_votes_to_gcs (string index out of range; 290)
[2024-04-02T03:15:06.774+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T03:15:06.789+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T03:42:55.946+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:42:55.951+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T03:42:55.952+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-04-02T03:42:55.958+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_and_upload_votes_to_gcs> on 2024-03-15 00:00:00+00:00
[2024-04-02T03:42:55.963+0000] {standard_task_runner.py:60} INFO - Started process 115 to run task
[2024-04-02T03:42:55.965+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'get_and_upload_votes_to_gcs', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmpnx87fcrp']
[2024-04-02T03:42:55.967+0000] {standard_task_runner.py:88} INFO - Job 130: Subtask get_and_upload_votes_to_gcs
[2024-04-02T03:42:55.993+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [running]> on host 308c9d5b795d
[2024-04-02T03:42:56.035+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='get_and_upload_votes_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-02T03:42:56.036+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_and_upload_votes() missing 1 required positional argument: 'bills_list'
[2024-04-02T03:42:56.040+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=upload_historical_congress_data, task_id=get_and_upload_votes_to_gcs, execution_date=20240315T000000, start_date=20240402T034255, end_date=20240402T034256
[2024-04-02T03:42:56.045+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 130 for task get_and_upload_votes_to_gcs (get_and_upload_votes() missing 1 required positional argument: 'bills_list'; 115)
[2024-04-02T03:42:56.058+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T03:42:56.072+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T04:03:13.962+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T04:03:13.966+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-02T04:03:13.966+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-04-02T04:03:13.972+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_and_upload_votes_to_gcs> on 2024-03-15 00:00:00+00:00
[2024-04-02T04:03:13.977+0000] {standard_task_runner.py:60} INFO - Started process 149 to run task
[2024-04-02T04:03:13.979+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'get_and_upload_votes_to_gcs', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmpbq7od_21']
[2024-04-02T04:03:13.982+0000] {standard_task_runner.py:88} INFO - Job 158: Subtask get_and_upload_votes_to_gcs
[2024-04-02T04:03:14.011+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.get_and_upload_votes_to_gcs scheduled__2024-03-15T00:00:00+00:00 [running]> on host 308c9d5b795d
[2024-04-02T04:03:14.056+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='get_and_upload_votes_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-02T04:03:14.057+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python/get_data.py", line 116, in get_and_upload_votes
    bills_list = ti.xcom_pull(key='bills_list', task_ids="get_bills_from_bq")
                 ^^
NameError: name 'ti' is not defined
[2024-04-02T04:03:14.062+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=upload_historical_congress_data, task_id=get_and_upload_votes_to_gcs, execution_date=20240315T000000, start_date=20240402T040313, end_date=20240402T040314
[2024-04-02T04:03:14.068+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 158 for task get_and_upload_votes_to_gcs (name 'ti' is not defined; 149)
[2024-04-02T04:03:14.115+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T04:03:14.129+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
