[2024-06-30T16:53:38.792+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_congress_data.upload_members_to_gcs scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-06-30T16:53:38.797+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_congress_data.upload_members_to_gcs scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-06-30T16:53:38.797+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-06-30T16:53:38.806+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): upload_members_to_gcs> on 2024-06-29 00:00:00+00:00
[2024-06-30T16:53:38.812+0000] {standard_task_runner.py:60} INFO - Started process 78 to run task
[2024-06-30T16:53:38.816+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_congress_data', 'upload_members_to_gcs', 'scheduled__2024-06-29T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/upload_congress_data.py', '--cfg-path', '/tmp/tmp9i2v8mfr']
[2024-06-30T16:53:38.819+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask upload_members_to_gcs
[2024-06-30T16:53:38.862+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_congress_data.upload_members_to_gcs scheduled__2024-06-29T00:00:00+00:00 [running]> on host 106864a7e5f7
[2024-06-30T16:53:38.906+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_congress_data' AIRFLOW_CTX_TASK_ID='upload_members_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T00:00:00+00:00'
[2024-06-30T16:53:38.999+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python/get_data.py", line 249, in upload_folder_to_gcs
    bucket = client.bucket(bucket_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/client.py", line 385, in bucket
    return Bucket(client=self, name=bucket_name, user_project=user_project)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/bucket.py", line 666, in __init__
    name = _validate_name(name)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/_helpers.py", line 144, in _validate_name
    raise ValueError("Bucket names must start and end with a number or letter.")
ValueError: Bucket names must start and end with a number or letter.
[2024-06-30T16:53:39.012+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=upload_congress_data, task_id=upload_members_to_gcs, execution_date=20240629T000000, start_date=20240630T165338, end_date=20240630T165339
[2024-06-30T16:53:39.018+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task upload_members_to_gcs (Bucket names must start and end with a number or letter.; 78)
[2024-06-30T16:53:39.035+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-30T16:53:39.052+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-30T17:00:47.925+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_congress_data.upload_members_to_gcs scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-06-30T17:00:47.937+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_congress_data.upload_members_to_gcs scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-06-30T17:00:47.938+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-06-30T17:00:47.959+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): upload_members_to_gcs> on 2024-06-29 00:00:00+00:00
[2024-06-30T17:00:47.974+0000] {standard_task_runner.py:60} INFO - Started process 76 to run task
[2024-06-30T17:00:47.979+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_congress_data', 'upload_members_to_gcs', 'scheduled__2024-06-29T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/upload_congress_data.py', '--cfg-path', '/tmp/tmpx62a376o']
[2024-06-30T17:00:47.983+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask upload_members_to_gcs
[2024-06-30T17:00:48.066+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_congress_data.upload_members_to_gcs scheduled__2024-06-29T00:00:00+00:00 [running]> on host 321f475acc45
[2024-06-30T17:00:48.174+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_congress_data' AIRFLOW_CTX_TASK_ID='upload_members_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T00:00:00+00:00'
[2024-06-30T17:00:48.387+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python/get_data.py", line 249, in upload_folder_to_gcs
    bucket = client.bucket(bucket_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/client.py", line 385, in bucket
    return Bucket(client=self, name=bucket_name, user_project=user_project)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/bucket.py", line 666, in __init__
    name = _validate_name(name)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/_helpers.py", line 144, in _validate_name
    raise ValueError("Bucket names must start and end with a number or letter.")
ValueError: Bucket names must start and end with a number or letter.
[2024-06-30T17:00:48.403+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=upload_congress_data, task_id=upload_members_to_gcs, execution_date=20240629T000000, start_date=20240630T170047, end_date=20240630T170048
[2024-06-30T17:00:48.415+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task upload_members_to_gcs (Bucket names must start and end with a number or letter.; 76)
[2024-06-30T17:00:48.439+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-30T17:00:48.483+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
